<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DalamudPackager" Version="13.1.0" />
    <PackageReference Include="DotNet.ReproducibleBuilds" Version="1.2.25">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Dalamud">
      <HintPath>..\..\..\..\AppData\Roaming\XIVLauncher\addon\Hooks\dev\Dalamud.dll</HintPath>
    </Reference>
    <Reference Include="Dalamud.Bindings.ImGui">
      <HintPath>..\..\..\..\AppData\Roaming\XIVLauncher\addon\Hooks\dev\Dalamud.Bindings.ImGui.dll</HintPath>
    </Reference>
    <Reference Include="Dalamud.Bindings.ImGuizmo">
      <HintPath>..\..\..\..\AppData\Roaming\XIVLauncher\addon\Hooks\dev\Dalamud.Bindings.ImGuizmo.dll</HintPath>
    </Reference>
    <Reference Include="Dalamud.Bindings.ImPlot">
      <HintPath>..\..\..\..\AppData\Roaming\XIVLauncher\addon\Hooks\dev\Dalamud.Bindings.ImPlot.dll</HintPath>
    </Reference>
    <Reference Include="FFXIVClientStructs">
      <HintPath>..\..\..\..\AppData\Roaming\XIVLauncher\addon\Hooks\dev\FFXIVClientStructs.dll</HintPath>
    </Reference>
    <Reference Include="InteropGenerator.Runtime">
      <HintPath>..\..\..\..\AppData\Roaming\XIVLauncher\addon\Hooks\dev\InteropGenerator.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Lumina">
      <HintPath>..\..\..\..\AppData\Roaming\XIVLauncher\addon\Hooks\dev\Lumina.dll</HintPath>
    </Reference>
    <Reference Include="Lumina.Excel">
      <HintPath>..\..\..\..\AppData\Roaming\XIVLauncher\addon\Hooks\dev\Lumina.Excel.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.ObjectPool">
      <HintPath>..\..\..\..\AppData\Roaming\XIVLauncher\addon\Hooks\dev\Microsoft.Extensions.ObjectPool.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\..\..\AppData\Roaming\XIVLauncher\addon\Hooks\dev\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="Serilog">
      <HintPath>..\..\..\..\AppData\Roaming\XIVLauncher\addon\Hooks\dev\Serilog.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="UslessPlayerInfo.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
